from pathlib import Path

WORKBOOK_PATH = Path("GrowForMe_CreditScoring_SyntheticData_v2 (1).xlsx")

WEIGHTS = {
    "cs_loan_repayment_history": 0.10,
    "cs_gender": 0.09,
    "cs_farm_location_risk": 0.06,
    "cs_mobile_money_score": 0.06,
    "cs_farm_size": 0.06,
    "cs_farmer_budget": 0.06,
    "cs_crop_type_score": 0.05,
    "cs_has_irrigation": 0.05,
    "cs_market_access": 0.05,
    "cs_seasonal_yield_score": 0.05,
    "cs_farmer_association": 0.04,
    "cs_insurance_subscription": 0.04,
    "cs_irrigation_scheme": 0.04,
    "cs_training_services": 0.04,
    "cs_livestock_ownership": 0.04,
    "cs_alternative_income": 0.04,
    "cs_has_insurance": 0.04,
    "cs_peer_endorsements": 0.03,
    "cs_soil_health": 0.03,
    "cs_motorbike_ownership": 0.02,
    "cs_digital_footprint": 0.01,
}

COMPONENT_MAX = {
    "cs_farm_location_risk": 100,
    "cs_gender": 75,
    "cs_mobile_money_score": 100,
    "cs_crop_type_score": 100,
    "cs_farmer_association": 75,
    "cs_motorbike_ownership": 75,
    "cs_farm_size": 100,
    "cs_farmer_budget": 100,
    "cs_loan_repayment_history": 100,
    "cs_seasonal_yield_score": 100,
    "cs_peer_endorsements": 100,
    "cs_has_irrigation": 90,
    "cs_irrigation_scheme": 80,
    "cs_market_access": 100,
    "cs_training_services": 100,
    "cs_livestock_ownership": 100,
    "cs_alternative_income": 100,
    "cs_has_insurance": 90,
    "cs_insurance_subscription": 80,
    "cs_digital_footprint": 100,
    "cs_soil_health": 100,
}

COMPONENT_LABELS = {
    "cs_farm_location_risk": "Farm location risk",
    "cs_gender": "Gender inclusivity",
    "cs_mobile_money_score": "Mobile money behavior",
    "cs_crop_type_score": "Crop diversification",
    "cs_farmer_association": "Farmer association membership",
    "cs_motorbike_ownership": "Motorbike ownership",
    "cs_farm_size": "Farm size and verification",
    "cs_farmer_budget": "Farmer budget",
    "cs_loan_repayment_history": "Loan repayment history",
    "cs_seasonal_yield_score": "Seasonal yield",
    "cs_peer_endorsements": "Peer endorsements",
    "cs_has_irrigation": "Irrigation type",
    "cs_irrigation_scheme": "Formal irrigation scheme",
    "cs_market_access": "Market access",
    "cs_training_services": "Training sessions",
    "cs_livestock_ownership": "Livestock value",
    "cs_alternative_income": "Alternative income",
    "cs_has_insurance": "Insurance type",
    "cs_insurance_subscription": "Insurance subscription",
    "cs_digital_footprint": "Digital footprint",
    "cs_soil_health": "Soil health",
}

CONTROLLABLE_COMPONENTS = [
    "cs_mobile_money_score",
    "cs_crop_type_score",
    "cs_farmer_association",
    "cs_motorbike_ownership",
    "cs_farm_size",
    "cs_farmer_budget",
    "cs_loan_repayment_history",
    "cs_seasonal_yield_score",
    "cs_peer_endorsements",
    "cs_has_irrigation",
    "cs_irrigation_scheme",
    "cs_market_access",
    "cs_training_services",
    "cs_livestock_ownership",
    "cs_alternative_income",
    "cs_has_insurance",
    "cs_insurance_subscription",
    "cs_digital_footprint",
    "cs_soil_health",
]

FEATURE_PLAIN_ENGLISH = {
    "drought_flood_index": "drought/flood risk",
    "savings_usd": "mobile savings",
    "payment_frequency": "mobile payment activity",
    "acres": "farm size",
    "repayment_rate": "loan repayment history",
    "yield_avg": "average seasonal yield",
    "farmer_budget_ghs": "farmer budget",
    "endorsements": "peer endorsements",
    "market_access_index": "market access",
    "training_sessions": "training participation",
    "livestock_value_usd": "livestock value",
    "alternative_income_usd": "alternative income",
    "digital_score": "digital activity",
    "soil_health_index": "soil health",
    "gender_female": "being female",
    "is_association_member": "association membership",
    "has_motorbike": "motorbike ownership",
    "satellite_verified": "satellite farm verification",
    "irrigation_scheme": "formal irrigation scheme participation",
    "insurance_subscription": "active insurance subscription",
    "irr_none": "using no irrigation",
    "irr_canal": "using canal irrigation",
    "irr_drip": "using drip irrigation",
    "ins_none": "having no insurance",
    "ins_crop": "having crop insurance",
    "ins_livestock": "having livestock insurance",
    "ins_both": "having both crop and livestock insurance",
    "has_staple": "staple crop production",
    "has_cash_crop": "cash crop production",
    "has_vegetable": "vegetable crop production",
    "has_other": "other crop production",
}
